### ISSUE TITLE
JsonDocument support

### ISSUE THREAD

**Issue by GuerrillaCoder** [evil-dr-nick/utf8jsonstreamreader#1]
Thanks for the class it works well with concrete types.  Anyway to get it to produce a `JsonDocument` ?

I need this so I can access properties with string.

**Comment by evil-dr-nick** [comment]
@GuerrillaCoder I'm guessing you want this for large streams - since for smaller single-object streams you can create a JsonDocument directly from the stream.

I'll take a look and see what I can do.

**Comment by evil-dr-nick** [comment]
@GuerrillaCoder I've added a GetJsonDocument() method for you. The source has moved into a sub-folder as I've also added some tests that I had lurking around.

**Comment by GuerrillaCoder** [comment]
Thanks Nick I really appreciate that.  I am just starting to get my head around your code so that addition is immensely helpful.
