### ISSUE TITLE
Related GitHub issue in Dotnet Core

### ISSUE THREAD

**Issue by om-ha** [evil-dr-nick/utf8jsonstreamreader#2]
Thanks for the very awesome contribution of yours! Appreciate sharing your fixes.

For reference, here's the [original issue](https://github.com/dotnet/runtime/issues/30328) on dotnet runtime repo.

Feel free to close this issue if you'd like. Just putting this out to be acknowledged of the ongoing original issue.

**Comment by evil-dr-nick** [comment]
Thanks for the link.
