### ISSUE TITLE
Add a call to Read() if firstSegment is null

### ISSUE THREAD

**Issue by oferns** [evil-dr-nick/utf8jsonstreamreader#5]
Hi, thanks for this. Super useful. One thing I noticed is if the stream has not been read yet then it fails. This can be fixed by adding these lines to DeserializePre (line 
 ```
if (firstSegment is null && this.Read()) {
    return DeserialisePre(out firstSegment, out firstSegmentStartIndex);
}
```

Cheers,
O

**Comment by om-ha** [comment]
Hey @oferns , thanks for the contribution.

You mean before [this line](https://github.com/evil-dr-nick/utf8jsonstreamreader/blob/5b4dbaff439186079088326f4a82ba9d465698a8/Utf8JsonStreamReader/Utf8JsonStreamReader.cs#L45) in the `Read()` method?

**Comment by om-ha** [comment]
You can get a permalink of the line and post it here or make a PullRequest (PR)

**Comment by oferns** [comment]
I'm so sorry. I didn't realize that I didnt finish the message! I meant on line 119 in the DeserialisePre. Gimme 10 mins and I'll create a PR. For a bit of context, I am passing the response stream from an HTTP call directly to this class.

**Comment by oferns** [comment]
Done

**Comment by om-ha** [comment]
Thanks for finding this problem and sharing its solution! Let's see what @evil-dr-nick  is gonna say.

**Comment by buffdaddy570** [comment]
suggest we close this issue based on the PR comments
