### ISSUE TITLE
Implementation question - Also do you plan to package this?

### ISSUE THREAD

**Issue by Simonl9l** [evil-dr-nick/utf8jsonstreamreader#8]
Hi @evil-dr-nick thanks for putting this is a repo, if a great pice of code! Don't Suppose it's available as nuget Package?

It seems it is referenced in a number of places include folks asking for things like this be be included in the DotNet explictity.

I've gone to some lengths to debug all the code to work out exactly how it works, I may be missing something; but have an observation.

Per the Deserialize (I renamed the method to align with DotNet naming) 
```C#
public T Deserialize<T>(JsonSerializerOptions? options = null)
        {
            var tokenStartIndex = DeserializePre(out var firstSegment, out var firstSegmentStartIndex);

            var newJsonReader =
                new Utf8JsonReader(new ReadOnlySequence<byte>(firstSegment!, firstSegmentStartIndex, _lastSegment!,
                    _lastSegmentEndIndex).Slice(tokenStartIndex, _jsonReader.Position), true, default);

            // deserialize value
            var result = JsonSerializer.Deserialize<T>(ref newJsonReader, options);

            DeserializePost();
            return result;
        }
```

Curious why the implementation creates the new Utf8JsonReader, as could one not just pass in the new ReadOnlySequence: 
``` C#
            var sequence =
                new ReadOnlySequence<byte>(firstSegment!, firstSegmentStartIndex, _lastSegment!,
                    _lastSegmentEndIndex).Slice(tokenStartIndex, _jsonReader.Position);

            // deserialize value
            var result = JsonSerializer.Deserialize<T>(sequence.FirstSpan(), options);
```
and save the Utf8JsonReader instance? 

Also it seem given the `<Nullable>enable</Nullable>`   project setting some methinks should be perhaps updated to indicate nullable return times ?

**Comment by evil-dr-nick** [comment]
Hi @Simonl9l 

I don't plan to package this as a nuget package. I just knocked this up a couple of years ago for a prototype I was working on, and haven't needed it since, so I don't spend time on it.

With regard to the Deserialise method, yes it can probably just take the sequence.FirstSpan instead of the json reader. It's written that way because the original version I based this on did it that way, and it wasn't broken, so I didn't fix it.

Can you clarify what you mean by 'updated to indicate nullable return times' ?

**Comment by Simonl9l** [comment]
Hi @evil-dr-nick thanks for the reply!
 
per packaging -all good, but for sure your the only one that’s published a very valid working class that is highly reusable. To confirm that it is under an open to use, restriction free license?

As an example the inner `Deserialise` method per above could return `null`, so the outer `Deserialise` Method on yourclass might be better indicate the `?` as nullable return to have the signature:

```C#
public T? Deserialize<T>(JsonSerializerOptions? options = null)
```

there are a few other methods that could also return null.

**Comment by evil-dr-nick** [comment]
Hi @Simonl9l ,

I wasn't sure the Deserialise method using the FirstSpan of the sequence would work for longer json strings, and indeed after testing it, it doesn't. The JsonSerializer.Deserialize call fails as it only sees the first chunk of the json, not the rest.

With regard to licenses, this repo is under the MIT license, i.e. open to use without restrictions and without liability or warranty.

With regard to nullable return types, the JsonSerializer.Deserialize<T> call shouldn't return null, it should throw if there are issues deserializing, so the return type of that method looks correct to me. Is there some specific situation with the underlying Deserialize call that you know will return null (that isn't documented) ? Same with GetJsonDocument() which uses JsonDocument.ParseValue().

Some of the the other public properties (e.g. GetComment) probably could return a null object, so I'll update those.

**Comment by evil-dr-nick** [comment]
Changes merged to master, thanks for your feedback!
